<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VerloskundigeSpiekt.Api\VerloskundigeSpiekt.Api.csproj" />
    <ProjectReference Include="..\..\src\VerloskundigeSpiekt.Infrastructure\VerloskundigeSpiekt.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
</Project>
