// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VerloskundigeSpiekt.Infrastructure;

#nullable disable

namespace VerloskundigeSpiekt.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712210032_AddMigrationRunState")]
    partial class AddMigrationRunState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("articles", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.ArticleSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_json");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heading");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Position")
                        .IsUnique();

                    b.ToTable("article_sections", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedTelephone")
                        .HasColumnType("text")
                        .HasColumnName("normalized_telephone");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "DisplayName");

                    b.HasIndex("PracticeId", "NormalizedEmail");

                    b.ToTable("contacts", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "Key")
                        .IsUnique();

                    b.ToTable("email_templates", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplateKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("email_template_keys", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_template_id");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "EmailTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("email_template_versions", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ETag")
                        .HasColumnType("text")
                        .HasColumnName("e_tag");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_object_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "StorageObjectName")
                        .IsUnique();

                    b.ToTable("file_metadata", "public", t =>
                        {
                            t.HasCheckConstraint("ck_file_metadata_size", "size_bytes >= 0 AND size_bytes <= 52428800");
                        });
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.MigrationAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MigrationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("migration_run_id");

                    b.Property<string>("SourceDocumentId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_system");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "SourceDocumentId")
                        .IsUnique();

                    b.ToTable("migration_aliases", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.MigrationRecordState", b =>
                {
                    b.Property<Guid>("MigrationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("migration_run_id");

                    b.Property<string>("SourceDocumentId")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("source_document_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_metadata_json");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MigrationRunId", "SourceDocumentId");

                    b.HasIndex("MigrationRunId", "Status");

                    b.ToTable("migration_record_states", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.MigrationRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("ChecksumAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_algorithm");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceChecksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_checksum");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("ToolVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tool_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RunId");

                    b.HasIndex("SourceChecksum", "ChecksumAlgorithm")
                        .IsUnique();

                    b.ToTable("migration_runs", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("practices", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticeInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invited_email");

                    b.Property<string>("InvitedEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email_normalized");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvitedEmailNormalized", "Status");

                    b.HasIndex("PracticeId", "InvitedEmailNormalized")
                        .IsUnique()
                        .HasFilter("status = 'Pending'");

                    b.ToTable("practice_invitations", "public", t =>
                        {
                            t.HasCheckConstraint("ck_practice_invitations_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticeMember", b =>
                {
                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PracticeId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PracticeId");

                    b.ToTable("practice_members", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "Slug")
                        .IsUnique();

                    b.ToTable("practice_pages", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePageSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_json");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("heading");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<Guid>("PracticePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_page_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "PracticePageId", "Position")
                        .IsUnique();

                    b.ToTable("practice_page_sections", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_id");

                    b.Property<Guid>("PracticePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_page_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId", "PracticePageId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("practice_page_versions", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subject");

                    b.Property<bool>("IsGlobalAdministrator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global_administrator");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("ActivePracticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_practice_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", "public");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.ArticleSection", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Article", "Article")
                        .WithMany("Sections")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Contact", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("Contacts")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplate", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplateVersion", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.EmailTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("PracticeId", "EmailTemplateId")
                        .HasPrincipalKey("PracticeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.FileMetadata", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("Files")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.MigrationRecordState", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.MigrationRun", "Run")
                        .WithMany("Records")
                        .HasForeignKey("MigrationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticeInvitation", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("Invitations")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticeMember", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("Members")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerloskundigeSpiekt.Domain.User", "User")
                        .WithMany("PracticeMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePage", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.Practice", "Practice")
                        .WithMany("Pages")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePageSection", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.PracticePage", "Page")
                        .WithMany("Sections")
                        .HasForeignKey("PracticeId", "PracticePageId")
                        .HasPrincipalKey("PracticeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePageVersion", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.PracticePage", "Page")
                        .WithMany("Versions")
                        .HasForeignKey("PracticeId", "PracticePageId")
                        .HasPrincipalKey("PracticeId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.UserPreference", b =>
                {
                    b.HasOne("VerloskundigeSpiekt.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("VerloskundigeSpiekt.Domain.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Article", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.EmailTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.MigrationRun", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.Practice", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EmailTemplates");

                    b.Navigation("Files");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.PracticePage", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("VerloskundigeSpiekt.Domain.User", b =>
                {
                    b.Navigation("PracticeMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
